"""
examples/iris_robustness.py
---------------------------
Demonstrates misslabel on the Iris dataset.

A logistic regression classifier is trained on increasingly corrupted labels,
generated by the F81 noise model at a grid of time values t. For each t we
record:

  - theoretical overall flip rate: sum_c pi_c * (1 - P(t)[c,c])
  - empirical flip rate from the injection
  - test accuracy of the classifier trained on corrupted labels

The result is a saturation curve: as t increases, labels become less
informative and accuracy falls toward the random baseline (1/k = 0.33).

Usage
-----
    python examples/iris_robustness.py

Optional dependency: matplotlib (for the plot).
If not installed, the table is printed and no plot is produced.
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder

from misslabel import inject, summary
from misslabel.matrix import estimate_pi, f81_transition_matrix


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

T_GRID = [0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0]
N_SPLITS = 5       # stratified k-fold for evaluation
RANDOM_STATE = 42


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------

iris = load_iris()
X = iris.data
y = iris.target.astype(np.int64)
class_names = iris.target_names  # ["setosa", "versicolor", "virginica"]

k = len(np.unique(y))
pi = estimate_pi(y, k)

print("Iris dataset")
print(f"  n={len(y)}, k={k}, classes={[str(c) for c in class_names]}")
print(f"  empirical pi = {pi.round(4)}")
print()


# ---------------------------------------------------------------------------
# Baseline: clean labels
# ---------------------------------------------------------------------------

clf = LogisticRegression(max_iter=200, random_state=RANDOM_STATE)
cv = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
baseline_acc = cross_val_score(clf, X, y, cv=cv, scoring="accuracy").mean()

print(f"Baseline accuracy (clean labels): {baseline_acc:.4f}")
print()


# ---------------------------------------------------------------------------
# Robustness experiment
# ---------------------------------------------------------------------------

print(
    f"{'t':>6}  "
    f"{'flip_rate_theoretical':>22}  "
    f"{'flip_rate_empirical':>20}  "
    f"{'accuracy':>10}"
)
print("-" * 68)

results = []

for t in T_GRID:
    # Inject noise
    injection = inject(y, t=t, pi=pi, random_state=RANDOM_STATE)
    y_noisy = injection.y_noisy

    # Audit: theoretical vs empirical flip rates
    report = summary(y, y_noisy, pi=pi, t=t)
    flip_theoretical = sum(
        pi[c] * v["flip_rate_theoretical"]
        for c, v in enumerate(report["per_class"].values())
    )
    flip_empirical = report["flip_rate"]

    # Evaluate classifier trained on noisy labels
    acc = cross_val_score(
        clf, X, y_noisy, cv=cv, scoring="accuracy"
    ).mean()

    results.append({
        "t": t,
        "flip_theoretical": flip_theoretical,
        "flip_empirical": flip_empirical,
        "accuracy": acc,
    })

    print(
        f"{t:>6.2f}  "
        f"{flip_theoretical:>22.4f}  "
        f"{flip_empirical:>20.4f}  "
        f"{acc:>10.4f}"
    )

print()
print(f"Random baseline (1/k): {1/k:.4f}")


# ---------------------------------------------------------------------------
# Plot (optional)
# ---------------------------------------------------------------------------

try:
    import matplotlib.pyplot as plt

    ts = [r["t"] for r in results]
    accs = [r["accuracy"] for r in results]
    flip_th = [r["flip_theoretical"] for r in results]
    flip_em = [r["flip_empirical"] for r in results]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 7), sharex=True)

    # Accuracy curve
    ax1.plot(ts, accs, marker="o", color="steelblue", label="Test accuracy")
    ax1.axhline(baseline_acc, linestyle="--", color="steelblue",
                alpha=0.5, label=f"Baseline ({baseline_acc:.3f})")
    ax1.axhline(1 / k, linestyle=":", color="gray",
                alpha=0.7, label=f"Random ({1/k:.3f})")
    ax1.set_ylabel("Accuracy")
    ax1.set_ylim(0, 1.05)
    ax1.legend()
    ax1.set_title("Classifier robustness under F81 label noise (Iris)")

    # Flip rate curve
    ax2.plot(ts, flip_th, marker="s", linestyle="--", color="tomato",
             label="Theoretical flip rate")
    ax2.plot(ts, flip_em, marker="o", color="tomato",
             label="Empirical flip rate")
    ax2.set_xlabel("t (noise parameter)")
    ax2.set_ylabel("Flip rate")
    ax2.set_ylim(0, 1.0)
    ax2.legend()

    plt.tight_layout()
    plt.savefig("examples/iris_robustness.png", dpi=150)
    print("Plot saved to examples/iris_robustness.png")
    plt.show()

except ImportError:
    print("matplotlib not installed : skipping plot.")
    print("Install with: pip install matplotlib")